### ISSUE TITLE
`--synced-folder` option is not respected

### ISSUE THREAD

**Issue by trapier** [CumulusNetworks/topology_converter#22]
## Summary
`--synced-folder` option is not respected.

## Steps to Reproduce

```
python topology_converter.py -ap libvirt examples/2switch_1server.dot --synced-folder
```

## Actual Outcome

sync is disabled.

```
$ grep device.vm.sync Vagrantfile 
    device.vm.synced_folder ".", "/vagrant", disabled: true
    device.vm.synced_folder ".", "/vagrant", disabled: true
    device.vm.synced_folder ".", "/vagrant", disabled: true
$
```

## Desired Outcome

sync is enabled (by Vagrant default).

```
$ grep device.vm.sync Vagrantfile 
$
```

**Comment by ericpulvino** [comment]
I'm sure I must have moved code around and broken this at some point. 

FYI: I've stopped trying to use it as I found it to be unreliable in vbox as virtualbox version, guest addition version, box version all need to align for it to work. On the libvirt side, having synced folders on requires an internet connection to turn up VX nodes since vagrant will try and install rsync under the covers to perform the sync.
