### ISSUE TITLE
purpose of vagrant interface?

### ISSUE THREAD

**Issue by wmclendon** [CumulusNetworks/topology_converter#28]
hi there.  like the tool.  looks very useful for simulating real interface names rather than have to change provisioning scripts for production from VX testing.

question I have is...what is the purpose of the 'vagrant' interface, renaming eth0 to this?  This breaks testing functions like with Ansible for example since the production deployment will not have a 'vagrant' interface.

I was able to get environment up and running using the converter but when my Ansible playbook runs through it does not account for the vagrant interface so my deploy bombs out when it goes to reload networking, since vagrant interface got removed (more accurately, I lose access and have to vagrant destroy).

Thanks.

**Comment by ericpulvino** [comment]
In short: the vagrant interface is used to regain the full control of "eth0" for use with production config.

In normal usage with Vagrant, you cannot control many aspects of the first interface which is used for Vagrant communication, this interface is typically named Eth0 as it is the first interface on the PCI bus for the VM. Imagine your production environment had a static eth0 IP address applied (or you wanted to hardcode the MAC address), traditional vagrant would not allow for this at all. The vagrant interface just simply renames the first interface on the pci bus to "vagrant" so that you can run your full production configuration against the eth0 interface without any limitations imposed on it by Vagrant. You'll see that instead of running automation from our local laptop/server which is hosting the simulation we actually run the automation from another VM that is located inside the simulation. In the case of the cldemo-vagrant ( https://github.com/CumulusNetworks/cldemo-vagrant/blob/master/cldemo_topology.png ) demos we simulation a full OOB network and run our automation from the OOB-server inside the simulation itself.

A byproduct of this workflow is that we're more realistically simulating the entire deployment workflow because we have an actual OOB network. 

Check out the "-c" option of topology converter which will automatically add a management switch and mgmt server to your existing topology ( Docs on that feature here --> https://github.com/CumulusNetworks/topology_converter/tree/master/documentation/auto_mgmt_network )
