### ISSUE TITLE
Why is libvirt set to use e1000 for the nic type instead of virtio?

### ISSUE THREAD

**Issue by linuxsimba** [CumulusNetworks/topology_converter#50]
relevant lines
https://github.com/CumulusNetworks/topology_converter/blob/master/templates/Vagrantfile.j2#L134

**Comment by ericpulvino** [comment]
The issue with using virtio is that most kernels do not yet have the [patch from Cumulus ](http://patchwork.ozlabs.org/patch/577135/) to be able to get/set speed settings on interfaces using the virtio driver. This doesn't matter for 99% of cases until you try to use the interface in a bond within a simulation. LACP tries to use the virtio interface in the bond but since it cannot retrieve a speed setting the LACP cannot use the interface and bonds will never form and lead to hours of troubleshooting and hair-pulling. We've worked to [upstream the change to Ubuntu](https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1581132) (although I'm not sure if most vagrant boxes already have the fix) but lack the time to submit it to every distro. 

As I'm typing this I see you've already [answered a serverfault question](http://serverfault.com/questions/738840/get-link-speed-of-an-virtio-net-network-adapter) on this topic with exactly what I've said above.
