### ISSUE TITLE
[auto_mgmt_network] add a standard way to inject authorized_keys inside hosts

### ISSUE THREAD

**Issue by mariusleu** [CumulusNetworks/topology_converter#72]
Right now the authorized_keys file is provisioned using ZTP, only inside cumulus-vx images.

It would be nice to have a way to inject that file automatically in the 'host' nodes as well, so that you have everything ready to use when you first log in to the oob-mgmt-server.

**Comment by ericpulvino** [comment]
The Cldemo-vagrant repository provides a simulation which is also built with topology converter, the ssh keyfile is pre-loaded there via the use of a helper script. There's a little bit of a chicken and egg problem because unless you pre-set it everywhere you won't necessarily know what it's going to be. 

The ability to do that is there today though.

**Comment by ericpulvino** [comment]
Here was the link to the cldemo-vagrant helper script for servers: https://github.com/CumulusNetworks/cldemo-vagrant/blob/master/helper_scripts/config_server.sh#L24 

I've leave this open for a bit in case I'm not understanding your comment.

**Comment by mariusleu** [comment]
I saw the cldemo-vagrant has a manual fashion of inserting the ssh keys.

On my first experience with topology converter, after using the "-c" argument, I was successfully able to ssh into the oob-mgm-server and from there on a leaf/spine node, but not on a host node. 
This happened because the leaf was a cumulus-vx image having the dhcp option "cumulus-provision-url" which will download the authorized keys (https://github.com/CumulusNetworks/topology_converter/blob/master/templates/auto_mgmt_network/dhcpd.conf.j2#L53) from the oob-mgmt-server

But if I would try to ssh into a host, which is an ordinary linux host, it would ask me for a password, because the oob-mgmt-server's public key doesn't exist in the compute01's authorized_keys.

**Comment by ericpulvino** [comment]
Gotcha this is a logical extension to the "-c" workflow where the environment is prepared a bit more for normal usage. This should be possible with some extension to the auto_mgmt_templates. Let me do some testing.

**Comment by ericpulvino** [comment]
After much reflection on this I think the tools are there to do this without formalized support. I am hesitant to implement the functionality because it forces me to make an assumption about what the Host OS will be and I'm not comfortable doing that.

However I see the logic in the ask and this could be implemented in your example via the use of a [passthrough attribute](https://github.com/CumulusNetworks/topology_converter/tree/master/documentation#passthrough-attributes)  in the oob-mgmt-server for "ssh_key"

In your the node definition of your topology.dot file you could specify
```
"oob-mgmt-server" [function="oob-server" vagrant="eth0" os="CumulusCommunity/vx_oob_server" version="1.0.4" memory="1024" config="./helper_scripts/config_oob_server.sh" ssh_key="12345" ]
"server01" [function="host" os="yk0/ubuntu-xenial" memory="512" config="./helper_scripts/auto_mgmt_network/config_server.sh" ]
```

Then creating a template file in ./templates/auto_mgmt_network/config_server.sh.j2 which contains the code to apply the ssh_key in your host OS.
in ./templates/auto_mgmt_network/config_server.sh.j2 
```
#!/bin/bash
useradd cumulus -m -s /bin/bash
echo "cumulus:CumulusLinux!" | chpasswd
sed "s/PasswordAuthentication no/PasswordAuthentication yes/" -i /etc/ssh/sshd_config
mkdir /home/cumulus/.ssh
echo "ssh-rsa {{ssh_key}}" >> /home/cumulus/.ssh/authorized_keys
chmod 700 -R /home/cumulus
chown -R cumulus:cumulus /home/cumulus
chmod 600 /home/cumulus/.ssh/*
chmod 700 /home/cumulus/.ssh
```
This would auto-generate the template with your passthrough attribute.
TC with the -c workflow is designed to be extensible via passthrough attributes for cases just like this.
